apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
        - name: customer-app
          image: acrca.azurecr.io/backend-image:v1
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-app
spec:
  type: ClusterIP
  selector:
    app: customer-app
  ports:
  - name: http
    port: 9000
    targetPort: 9000
